name: Greeting Workflow
on: [push]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # This "downloads" your repo onto the runner

      - name: Run a greeting
        run: echo "The CI pipeline has successfully started!"

      - name: Run Python Tests
        run: python3 test_calc.py
